### ISSUE TITLE
Agent cannot be correctly instantiated by the Use API

### ISSUE THREAD

**Issue by lopesdasilva** [deveth0/elasticsearch-aem#1]
Hi, 
After installing both osgi bundles (wrapper and elasticsearch-aem) when I try to open the new replication agent, I get the error: Agent cannot be correctly instantiated by the Use API

![screen shot 2017-05-19 at 17 36 04](https://cloud.githubusercontent.com/assets/1013126/26257730/a7f3107a-3cb9-11e7-8d40-ff6fa6963b91.png)

![screen shot 2017-05-19 at 17 35 18](https://cloud.githubusercontent.com/assets/1013126/26257702/940ce55e-3cb9-11e7-9d43-1816758061f5.png)
 
Details:
AEM version: 6.2

`Caused by: org.apache.sling.scripting.sightly.SightlyException: Identifier de.dev.eth0.elasticsearch.aem.indexing.controller.Agent cannot be correctly instantiated by the Use API
	at org.apache.sling.scripting.sightly.impl.engine.extension.use.UseRuntimeExtension.call(UseRuntimeExtension.java:89)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.call(RenderContextImpl.java:66)
	at org.apache.sling.scripting.sightly.apps.deveth0_elastic.components.page.elasticSearchIndexAgent.SightlyJava_elasticSearchIndexAgent.render(SightlyJava_elasticSearchIndexAgent.java:61)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderUnit.render(RenderUnit.java:54)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.evaluateScript(SightlyScriptEngine.java:92)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.eval(SightlyScriptEngine.java:78)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:388)
	... 140 more
Caused by: org.apache.sling.models.factory.MissingElementsException: Could not inject all required fields into class de.dev.eth0.elasticsearch.aem.indexing.controller.Agent
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:593)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:335)
	at org.apache.sling.models.impl.ModelAdapterFactory.createModel(ModelAdapterFactory.java:223)
	at org.apache.sling.scripting.sightly.models.impl.SlingModelsUseProvider.provide(SlingModelsUseProvider.java:125)
	at org.apache.sling.scripting.sightly.impl.engine.extension.use.UseRuntimeExtension.call(UseRuntimeExtension.java:84)
	... 146 more
	Suppressed: org.apache.sling.models.factory.MissingElementException: Could not inject private java.lang.String de.dev.eth0.elasticsearch.aem.indexing.controller.Agent.enabled
		at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:598)
		... 150 more
	Caused by: org.apache.sling.models.factory.ModelClassException: No injector returned a non-null value!
		at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:513)
		at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:596)
		... 150 more`

**Comment by deveth0** [comment]
Can you check, if all bundles are running?

**Comment by lopesdasilva** [comment]
Yes both bundle are running.

<img width="1441" alt="screen shot 2017-05-19 at 18 15 18" src="https://cloud.githubusercontent.com/assets/1013126/26259050/2ba04dca-3cbf-11e7-8f4d-0fc9b948e4ab.png">

**Comment by deveth0** [comment]
Please check, if you have setup the OSGi configuration (just in case) and post, what the properties of the replication agent are (e.g. from CRX).

**Comment by lopesdasilva** [comment]
Hi, Thanks for your reply.
Here they go:

![screen shot 2017-05-22 at 08 51 11](https://cloud.githubusercontent.com/assets/1013126/26297698/e6490794-3ecb-11e7-8421-ec5afffdf39e.png)
![screen shot 2017-05-22 at 08 50 57](https://cloud.githubusercontent.com/assets/1013126/26297699/e7096b88-3ecb-11e7-9e0c-fac3328c33ff.png)

**Comment by lopesdasilva** [comment]
The problem is here:
This annotation is failing when it's not set.
`@ValueMapValue
  private String enabled;`
[Agent.java](https://github.com/deveth0/elasticsearch-aem/blob/ed0e09db3fc6311a843259a15eb8ca47455cb596/integration/src/main/java/de/dev/eth0/elasticsearch/aem/indexing/controller/Agent.java)

**Comment by deveth0** [comment]
pullrequests welcome ;)

**Comment by lopesdasilva** [comment]
done #2

**Comment by deveth0** [comment]
Thank you :)
